query (
  $page: Int,
  $perPage: Int,
  $genres: [String],
  $isAdult: Boolean = true, # Assign default value if isAdult is not included in our query variables 
  $search: String
) {
  Page (page: $page, perPage: $perPage) {
    pageInfo {
      total
      perPage
      currentPage
      lastPage
      hasNextPage
    }
    media (
      genre_in: $genres,
      isAdult: $isAdult,
      search: $search,
    ) {
      id
      title {
        userPreferred
      }
      genres
      averageScore
      popularity
      season
      description
      synonyms
        coverImage {
          medium
        }
    }
  }
}